# Generated by Django 6.0.7 on 2026-07-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='sessions_app.session')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('total_frames', models.IntegerField(default=0)),
                ('avg_fps', models.FloatField(default=0.0)),
                ('total_emotion_changes', models.IntegerField(default=0)),
                ('face_count_max', models.IntegerField(default=0)),
                ('detection_accuracy_estimate', models.FloatField(default=0.0)),
                ('emotion_distribution', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='sessions_app.session')),
            ],
            options={
                'db_table': 'analytics',
            },
        ),
    ]
