# Generated by Django 6.0.7 on 2026-07-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('angry', 'Angry'), ('neutral', 'Neutral'), ('fear', 'Fear'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('uncertain', 'Uncertain')], max_length=20)),
                ('confidence', models.FloatField()),
                ('face_count', models.IntegerField(default=1)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('frame_number', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_logs', to='sessions_app.session')),
            ],
            options={
                'db_table': 'emotion_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FaceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('face_index', models.IntegerField(default=0)),
                ('bbox_x', models.IntegerField(default=0)),
                ('bbox_y', models.IntegerField(default=0)),
                ('bbox_w', models.IntegerField(default=0)),
                ('bbox_h', models.IntegerField(default=0)),
                ('emotion', models.CharField(blank=True, max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_logs', to='sessions_app.session')),
            ],
            options={
                'db_table': 'face_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
