# Generated by Django 6.0.7 on 2026-07-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotionlog',
            name='face_index',
            field=models.IntegerField(default=0),
        ),
    ]
