# Generated by Django 6.0.7 on 2026-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('error', 'Error')], default='active', max_length=20)),
                ('total_frames', models.IntegerField(default=0)),
                ('avg_fps', models.FloatField(default=0.0)),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-start_time'],
            },
        ),
    ]
