# Generated by Django 6.0.7 on 2026-07-19 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('face_index', models.IntegerField(default=0)),
                ('smile_detected', models.BooleanField(default=False)),
                ('smile_score', models.FloatField(default=0.0)),
                ('left_eye_open', models.BooleanField(default=True)),
                ('right_eye_open', models.BooleanField(default=True)),
                ('blink_detected', models.BooleanField(default=False)),
                ('blink_count', models.IntegerField(default=0)),
                ('head_direction', models.CharField(choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right'), ('up', 'Up'), ('down', 'Down'), ('unknown', 'Unknown')], default='center', max_length=20)),
                ('yaw_angle', models.FloatField(default=0.0)),
                ('pitch_angle', models.FloatField(default=0.0)),
                ('face_present', models.BooleanField(default=True)),
                ('face_count', models.IntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='sessions_app.session')),
            ],
            options={
                'db_table': 'behavior_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
